services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq

  # destination:
  #   build:
  #     context: .
  #     dockerfile: ./apps/destination/Dockerfile
  #     target: development
  #   command: npm run start:dev destination
  #   env_file:
  #     - ./apps/destination/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3002:3002'
  #   depends_on:
  #     - rabbitmq
  #     - auth
    
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
