services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    environment:            
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq

  destination:
    build:
      context: .
      dockerfile: ./apps/destination/Dockerfile
      target: development
    command: npm run start:dev destination
    environment:            
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - ./apps/destination/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
    depends_on:
      - rabbitmq
      - auth

  trip:
    build:
      context: .
      dockerfile: ./apps/trip/Dockerfile
      target: development
    command: npm run start:dev trip
    environment:            
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - ./apps/trip/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
    depends_on:
      - rabbitmq
      - auth
      - destination

  # review:
  #   build:
  #     context: .
  #     dockerfile: ./apps/review/Dockerfile
  #     target: development
  #   command: npm run start:dev review
  #   environment:            
  #     - TZ=Asia/Ho_Chi_Minh
  #   env_file:
  #     - ./apps/review/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3004:3004'
  #   depends_on:
  #     - rabbitmq
  #     - auth
  #     - destination
    
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
