name: deploy

on:
  workflow_run:
    workflows: ["build-publish"]
    types:
      - completed

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD Helm Repo
        uses: actions/checkout@v3
        with:
          repository: MarshTravel/ProjectMarshTravel-CD
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Helm and kubectl
        run: |
          sudo apt-get install kubectl
          sudo apt-get install helm
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          ls 
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Setup gke-gcloud-auth-plugin'
        run: 'gcloud components install gke-gcloud-auth-plugin'

      - name: 'Config Gcloud cluster in kubectl'
        run: |
          gcloud container clusters get-credentials marshtravel --region=us-central1-a
          kubectl config current-context
      

      
      